{% set name = "pypmc" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8154fa9d2c71055e899a8a4f32c3dc7cdb3a57ba76b848fd653827301d33959d

build:
  number: 0
  python_version_independent: true  # [py >= 311]
  skip: true  # [py <= 38 or python_impl == "pypy" or win]
  script: {{ PYTHON }} -m pip install .[plotting,parallelization] -vv

requirements:
  build:
    # cython project, so need a compiler
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cython >=0.21
  host:
    - python-abi3                  # [py >= 311]
    - python
    - pip
    - cython >=0.21
    - numpy
    - mpi4py
    - scipy
    - setuptools >=40.8.0

  run:
    - python
    - mpi4py
    - {{ pin_compatible('numpy', min_pin='1.2.6') }}
    - scipy
    - matplotlib-base


test:
  imports:
    - pypmc

about:
  home: https://pypmc.github.io/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: pypmc is a python package focusing on adaptive importance sampling

  description: |
    pypmc is a python package focusing on adaptive importance sampling. It can be used for integration and sampling from a user-defined target density. A typical application is Bayesian inference, where one wants to sample from the posterior to marginalize over parameters and to compute the evidence. The key idea is to create a good proposal density by adapting a mixture of Gaussian or student’s t components to the target density. The package is able to efficiently integrate multimodal functions in up to about 30-40 dimensions at the level of 1% accuracy or less. For many problems, this is achieved without requiring any manual input from the user about details of the function. Importance sampling supports parallelization on multiple machines via mpi4py.

    Useful tools that can be used stand-alone include:

    * importance sampling (sampling & integration)
    * adaptive Markov chain Monte Carlo (sampling)
    * variational Bayes (clustering)
    * population Monte Carlo (clustering)

  doc_url: https://pypmc.github.io/
  dev_url: https://github.com/pypmc/pypmc/

extra:
  recipe-maintainers:
    - JohannesBuchner
